name: Mirror to GitLab

on:
  push:
    branches:
      - main
      - v*.*.x

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Mirror to Gitlab Repository
      uses: actions/checkout@v3

    - name: Push to GitLab
      run: |
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"
        git remote add gitlab "https://mo271:${{ secrets.GITLAB_MIRROR }}@gitlab.com/mo271/jpeg-xlm.git"
        git push  gitlab $BRANCH_NAME:$BRANCH_NAME
